apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: zoman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: zoman-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: zoman
spec:
  selector:
    app: agent-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
