apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.3.0
        ports:
        - containerPort: 3000
          name: web
        env:
        # Default admin password (change after first login!)
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "Zoman2026!SecureGrafana#"
        # Server settings
        - name: GF_SERVER_ROOT_URL
          value: "https://zoman.switzerlandnorth.cloudapp.azure.com/grafana/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        # Anonymous access (optional - for demo purposes)
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        # Install plugins
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - name: web
    port: 3000
    targetPort: 3000

---
# ConfigMap for Grafana provisioning (auto-configure Prometheus datasource)
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
